export const STATUS = {
  SUCCESS_NUM: 200,
  OK: 201,
  OK_TEXT: 'OK',
  SUCCESS: 'success',
  UNAUTHORIZED: 401,
  ERROR: 500,
  UNPROCESSABLE_ENTITY: 422,
  FAILED: 'failed',
  FORBIDDEN: 403,
  NOT_FOUND: 404,
}
